version: '3.9'

services:
  web:
    container_name: web
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata fixtures/initial_data.json &&
             python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"


  db:
    image: postgres:14
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
