version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-1hjf#rg!4gh%gpdqg(r2c@axf-#3s_8flb$S$1%ubimo+8w4e@nj"
#      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
#      - "DJANGO_ZARINPAL_MERCHANT_ID=${DOCKER_COMPOSE_DJANGO_ZARINPAL_MERCHANT_ID}"


  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"