# Generated by Django 4.2 on 2023-04-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
