# Generated by Django 4.2 on 2025-03-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
